"use client";
import { TrendingUp, Users, Award, Briefcase, DollarSign, Database } from "lucide-react";

interface PlacementStats {
  domain: string;
  rate: string;
  avgDegreeP: string;
  avgSalary: string;
  workexWithRate: string;
  workexWithoutRate: string;
  overallRate: string;
  placedTotal: number;
  total: number;
}

interface PlacementPanelProps {
  tip: string;
  stats: PlacementStats | null;
  domain: string;
  loading: boolean;
  error?: string;
}

function StatCard({ icon, label, value, sub }: { icon: React.ReactNode; label: string; value: string; sub?: string }) {
  return (
    <div className="bg-white/5 border border-white/10 rounded-xl p-4 flex items-start gap-3">
      <div className="p-2 rounded-lg bg-violet-500/10 text-violet-400">{icon}</div>
      <div>
        <p className="text-xs text-slate-500 mb-0.5">{label}</p>
        <p className="text-lg font-bold text-slate-200">{value}</p>
        {sub && <p className="text-xs text-slate-600 mt-0.5">{sub}</p>}
      </div>
    </div>
  );
}

export default function PlacementPanel({ tip, stats, domain, loading, error }: PlacementPanelProps) {
  if (loading) {
    return (
      <div className="space-y-4 animate-pulse">
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          {Array.from({ length: 6 }).map((_, i) => (
            <div key={i} className="h-20 bg-white/5 border border-white/10 rounded-xl" />
          ))}
        </div>
        <div className="h-32 bg-white/5 border border-white/10 rounded-2xl" />
        <p className="text-center text-sm text-slate-500">Analyzing placement data with Llama 3...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-500/10 border border-red-500/20 rounded-2xl p-4 text-red-300 text-sm">
        ⚠ {error}
      </div>
    );
  }

  if (!tip) return null;

  return (
    <div className="space-y-5">
      {/* Dataset badge */}
      <div className="flex items-center gap-2 px-3 py-2 bg-blue-500/10 border border-blue-500/20 rounded-xl w-fit">
        <Database size={14} className="text-blue-400" />
        <span className="text-xs text-blue-300 font-medium">
          Powered by Kaggle Campus Placement Dataset · {stats?.total ?? 215} students · {domain}
        </span>
      </div>

      {/* Stats grid */}
      {stats && (
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          <StatCard
            icon={<TrendingUp size={16} />}
            label={`${domain} Placement Rate`}
            value={`${stats.rate}%`}
            sub="of students in this domain"
          />
          <StatCard
            icon={<Award size={16} />}
            label="Avg UG % (Placed)"
            value={`${stats.avgDegreeP}%`}
            sub="degree percentage"
          />
          <StatCard
            icon={<DollarSign size={16} />}
            label="Avg Salary"
            value={`₹${parseInt(stats.avgSalary).toLocaleString("en-IN")}`}
            sub="for placed students"
          />
          <StatCard
            icon={<Briefcase size={16} />}
            label="With Work Experience"
            value={`${stats.workexWithRate}%`}
            sub="placement rate"
          />
          <StatCard
            icon={<Users size={16} />}
            label="Without Work Experience"
            value={`${stats.workexWithoutRate}%`}
            sub="placement rate"
          />
          <StatCard
            icon={<TrendingUp size={16} />}
            label="Overall Placement"
            value={`${stats.overallRate}%`}
            sub={`${stats.placedTotal}/${stats.total} placed`}
          />
        </div>
      )}

      {/* AI Tip */}
      <div className="bg-gradient-to-br from-violet-600/10 to-indigo-600/10 border border-violet-500/20 rounded-2xl p-5">
        <div className="flex items-center gap-2 mb-3">
          <TrendingUp size={16} className="text-violet-400" />
          <span className="text-sm font-semibold text-violet-300 uppercase tracking-wide">
            Data-Backed Placement Advice
          </span>
        </div>
        <div className="space-y-2">
          {tip.split("\n").filter(Boolean).map((line, i) => (
            <p key={i} className="text-slate-300 text-sm leading-relaxed">
              {line}
            </p>
          ))}
        </div>
        <p className="text-xs text-slate-600 mt-4 border-t border-white/5 pt-3">
          Generated by Llama 3 (Groq) using real Kaggle campus recruitment data
        </p>
      </div>
    </div>
  );
}
